### ISSUE TITLE
ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'

### ISSUE THREAD

**Issue by sthapa320** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#10]
Any ideas on resolving this error? My system meets all of the requirements to run this program

**Comment by MahmudulAlam** [comment]
@sthapa320 
Hi,
Sorry for the late reply. First, make sure you have Visual Studio C++ installed in your pc. Then check the version of cython, it should be Cython==0.29.2. 
Let me know if the issue is fixed or not.

**Comment by sthapa320** [comment]
Hello, 

Thank you for your reply. I got the model working a couple days ago! 

-Sam

**Comment by kunalchamoli** [comment]
same thing is happening to me on ubuntu, and cython is already installed  (version-0.29.32)

**Comment by MahmudulAlam** [comment]
what python version are you using? try with python 3.6

**Comment by kunalchamoli** [comment]
yes, i am using python 3.6

**Comment by kunalchamoli** [comment]
can you build the files again or give a python module for the same instead of cython.

**Comment by MahmudulAlam** [comment]
@kunalchamoli 

Hi, 
I have fixed the issue and updated the repository. Please go through the README and follow the instruction. It should be fine now. Let me know.
