### ISSUE TITLE
run the code in google colab

### ISSUE THREAD

**Issue by gzx666** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#12]
I have followed your step on https://github.com/MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells/wiki/A-Step-by-Step-Guide-of-How-to-Run-the-Code but when I do the step 3, runing code by command "python detect.py" on google colab, it report an error below.
 
![image](https://user-images.githubusercontent.com/30193272/129466628-0d6fe9dc-e80c-4a3f-9fab-55762537ef96.png)

**Comment by MahmudulAlam** [comment]
@gzx666 
Hi, I think cython is missing and you need to install cython==0.29.23

**Comment by WidianaAR** [comment]
![image](https://user-images.githubusercontent.com/89754513/132612260-aa0f6751-30f7-4598-af3a-f1988c13d865.png)
Help, it's still not working

**Comment by MahmudulAlam** [comment]
Seems like you are using Python 3.7. I tested on Python 3.6 and it worked without any issue. Can you please change the python version and let me know?

**Comment by WidianaAR** [comment]
oh it works, thank u

**Comment by MahmudulAlam** [comment]
Great!

**Comment by akochman** [comment]
> oh it works, thank u

are you using a local runtime? if not what method was successful for modifying the hosted runtime to 3.6?
thanks!

**Comment by HebaAhmedBackar** [comment]
> oh it works, thank u

I've already tried that and I'm still getting the same error...is there anyway I could get a link to the project on colab so i can take a look at it and hopefully figure out where I'm going wrong..
thanks!

**Comment by MahmudulAlam** [comment]
@7HAB 
Can you please share your error message here?

**Comment by 7HAB** [comment]
> @7HAB
> Can you please share your error message here?
hi, i really appreciate you reaching out to help :)
<img width="1123" alt="Screen Shot 2021-11-25 at 9 23 21 PM" src="https://user-images.githubusercontent.com/48590428/143493219-66f3098f-3935-4df3-8980-b6358f059a93.png">
python version 3.6.9
python 0.29.23

**Comment by MahmudulAlam** [comment]
@7HAB 
I built the darkflow module for Linux. I should work now without any issue. Can you please clone the repo again and test it in colab and verify whether it is working or not? Please let me know.

**Comment by MahmudulAlam** [comment]
If you are getting ": cannot connect to X server" in ```colab``` then comment line 103 ```cv2.imshow``` and use ```matplotlib``` for visualizing.

**Comment by 7HAB** [comment]
> @7HAB
> I built the darkflow module for Linux. I should work now without any issue. Can you please clone the repo again and test it in colab and verify whether it is working or not? Please let me know.

It works! thank you so much for your help 😊

**Comment by Jagan3534** [comment]
can you please help me in this 


`Traceback (most recent call last):
  File "C:/Users/jagan/Downloads/Automatic-Identification-and-Counting-of-Blood-Cells-master/Automatic-Identification-and-Counting-of-Blood-Cells-master/test.py", line 26, in <module>
    output = tfnet.return_predict(image)
  File "C:\Users\jagan\Downloads\Automatic-Identification-and-Counting-of-Blood-Cells-master\Automatic-Identification-and-Counting-of-Blood-Cells-master\darkflow\net\flow.py", line 83, in return_predict
    'Image is not a np.ndarray'

AssertionError: Image is not a np.ndarray
`
