### ISSUE TITLE
can you please help me in this

### ISSUE THREAD

**Issue by Jagan3534** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#13]
can you please help me in this 

`Traceback (most recent call last):
  File "C:/Users/jagan/Downloads/Automatic-Identification-and-Counting-of-Blood-Cells-master/Automatic-Identification-and-Counting-of-Blood-Cells-master/test.py", line 26, in <module>
    output = tfnet.return_predict(image)
  File "C:\Users\jagan\Downloads\Automatic-Identification-and-Counting-of-Blood-Cells-master\Automatic-Identification-and-Counting-of-Blood-Cells-master\darkflow\net\flow.py", line 83, in return_predict
    'Image is not a np.ndarray'

AssertionError: Image is not a np.ndarray
`

_Originally posted by @Jagan3534 in https://github.com/MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells/issues/12#issuecomment-983766303_

**Comment by MahmudulAlam** [comment]
@Jagan3534 

Hi, can you please follow these steps: https://github.com/MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells/wiki/A-Step-by-Step-Guide-of-How-to-Run-the-Code 

Running this code is straightforward and should work without an issue.

**Comment by Jagan3534** [comment]
Yes sir it work sir but we want to give input as our image sir
Its giving error sir
Can you please give us solution sir



Thank you sir

**Comment by MahmudulAlam** [comment]
In that case, please share your code, its hard to tell just by seeing the error message.

**Comment by Jagan3534** [comment]
Their no error in your code sir its running cool but it won't take our own
image sir when we insert our own image in it. it showing error like before
one sir

We need to take code our img as input and it want to show in that image sir.

**Comment by MahmudulAlam** [comment]
Try loading the image using cv2

**Comment by MahmudulAlam** [comment]
Follow this file. Put your image directory to the image name : https://github.com/MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells/blob/c8f4e95359ee7ba5a8cff60200cec894b6d3f407/detect.py#L109

**Comment by Jagan3534** [comment]
thank you so much sir 
its working thank you sir
its my first project sir 
thank you for helping me a lot sir

**Comment by MahmudulAlam** [comment]
Glad to know that it is working.

**Comment by Jagan3534** [comment]
Awesome, thanks!
