### ISSUE TITLE
How did you label the data ?

### ISSUE THREAD

**Issue by Jagadeeswar-reddy-c** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#14]
Hello sir,
How did you label the data ? sir

Thank you sir

**Comment by Jagadeeswar-reddy-c** [comment]
hello sir
Can you please give reply for us sir

**Comment by MahmudulAlam** [comment]
Using the LabelIMG annotation tool from GitHub: https://github.com/tzutalin/labelImg
