### ISSUE TITLE
getting os error: file not found while running in google colab

### ISSUE THREAD

**Issue by Baggyyyy** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#16]
![image](https://user-images.githubusercontent.com/113238304/203826693-7cca4880-8d22-4f34-83af-99c23a548384.png)
I HAVE UPLOADED WEIGHTS IN THE CURRENT DIRECTORY..BUT ITS GIVING ERROR LIKE THIS WHILE TRYING TO RUN detect.py
### PLEASE DO HELP ME SIR.

**Comment by MahmudulAlam** [comment]
Please share the colab link here.

**Comment by MahmudulAlam** [comment]
Here is how I run the code in colab: https://colab.research.google.com/drive/1NnBYK-SZitrH_gqWkyrCVJbu5b8AgXxI?usp=sharing

**Comment by Baggyyyy** [comment]
Thanks a lot sir

**Comment by Baggyyyy** [comment]
Is there any possible way to find the accuracy, mAP and precision using the pretrained weights provided here in colab,sir

**Comment by MahmudulAlam** [comment]
That means you need to install cv2. pip install opencv-python
