### ISSUE TITLE
Issue on running code

### ISSUE THREAD

**Issue by Aravind6996** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#17]
Hi,
Thanks for this wonderful project.
I am getting some issue while running python detect.py command. Below are the details and it's screenshot. It just gets stuck for lon time. Please refer the screenshots attached.
![Screenshot from 2023-01-24 16-28-09](https://user-images.githubusercontent.com/123463596/214274510-f9f62d9a-1d2a-4ebb-9cf5-bba51079c5f8.png)
![Screenshot from 2023-01-24 16-27-57](https://user-images.githubusercontent.com/123463596/214274515-342322ed-29ab-47a7-a9fc-60780807a4fb.png)

**Comment by MahmudulAlam** [comment]
@Aravind6996 
Hello, you can try to print at various points to figure out exactly where the code gets stuck. I haven't faced any issue this like. It could be a GPU issue.

**Comment by malik24ali** [comment]
there is a issue in darkflow... i ran it on vs code

**Comment by MahmudulAlam** [comment]
what is the issue?
