### ISSUE TITLE
have you published any paper about your work？

### ISSUE THREAD

**Issue by GloriaZLQ** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#3]

**Comment by MahmudulAlam** [comment]
Yes. The [paper](http://ietdl.org/t/kmgztb) has been published recently in IET healthcare technology letters journal.

**Comment by afaq-ahmad** [comment]
hi, how you have converted square bounding box to circular ?

**Comment by MahmudulAlam** [comment]
Hello, to convert square bounding box to circular you have to estimate the center and the radius of the circle from top left and bottom right coordinates of the square bounding box which is discussed in the [paper](https://digital-library.theiet.org/docserver/fulltext/10.1049/htl.2018.5098/HTL.2018.5098.pdf?expires=1558195110&id=id&accname=480431&checksum=52EEC3B3AC129D31F1CAA264B715F6D9). I have attached the screenshot of the equations here. 
![ans](https://user-images.githubusercontent.com/37298971/57971950-78404f00-79b6-11e9-9c3d-b6a6ffc3f7ee.png)
Hope this is helpful.

**Comment by afaq-ahmad** [comment]
MahmudulAlam  understood, thanks
