### ISSUE TITLE
Weights issue

### ISSUE THREAD

**Issue by kitcatkai** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#4]
Hi,

Thanks for the awesome work!

I am trying to replicate your work but run into some issues with your weights.

I have downloaded your weights but it comes in different formats. For darkflow, the weights file is `.weights` but I cannot find this file type from your weights. 

(1)Do you have .weights file?

I tried renaming your file `tiny-yolo-voc-3c-3750.meta` and `tiny-yolo-voc-3c-3750.data-00000-of-00001` at file size, 63mb and 189mb, to .weights file but the weight just does not match with your architecture, with the error message below when I run this command, using the original darkflow github repo

```
flow --model cfg/tiny-yolo-voc-3c.cfg --load bin/tiny-yolo-voc-3c.weights
```
Note: I copy your `tiny-yolo-voc-3c.cfg` and rename your file to `tiny-yolo-voc-3c.weights` to run the above command.

Error message:

```
AssertionError: expect 63082056 bytes, found 63676889
```

**Comment by GloriaZLQ** [comment]
have you solved it，i meet the same problem.

**Comment by MahmudulAlam** [comment]
Hello. 
First of all, ```.weights``` is the weight file format of [Darknet](https://pjreddie.com/darknet/), not darkflow. So, you should not change the weight file extensions. 
Secondly, ```.cfg``` or configuration file contains the network architecture from which network is built so you should not change that extension too. 
Finally, the command line arguments are not implemented for blood cell detection. So, you may use an IDE to run the code.
I will try to create a wiki providing step by step guideline of how to run the code beginning from cloning the repo as soon as possible.

**Comment by MahmudulAlam** [comment]
I have created this [step by step guideline](https://github.com/MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells/wiki/A-Step-by-Step-Guide-of-How-to-Run-the-Code) of how to run the code. 
Hope this helps.
