### ISSUE TITLE
how to train on my own dataset

### ISSUE THREAD

**Issue by GloriaZLQ** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#6]
I want use you code to train on my own dataset ,and which file or code should i changed?

**Comment by MahmudulAlam** [comment]
I have created a wiki on [How to Train on Your Dataset](https://github.com/MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells/wiki/How-to-Train-on-Your-Dataset). 
Hope it helps.

**Comment by GloriaZLQ** [comment]
thanks !!!

**Comment by GloriaZLQ** [comment]
when run 
`python flow --model cfg/tiny-yolo-voc-3c.cfg --load bin/tiny-yolo-voc.weights --train --gpu .7 --annotation Dataset/Training/Annotations --dataset Dataset/Training/Images --lr 1e-3 --epoch 100`
python: can't open file 'flow': [Errno 2] No such file or directory,is the file "flow"in \darkflow\net???

**Comment by MahmudulAlam** [comment]
I have uploaded flow. Download the file.

**Comment by GloriaZLQ** [comment]
oh,i see
