### ISSUE TITLE
Failed to run Blood Cell Detection.py

### ISSUE THREAD

**Issue by ThanhDEHA** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#7]
Thank for your source code. 
When I try this github, follow the instruction in wiki, I meet following error. I hope you can help me. 

`(tf_gpu) D:\Download\Automatic-Identification-and-Counting-of-Blood-Cells\Automatic-Identification-and-Counting-of-Blood-Cells-master>python "Blood Cell Detection.py"
Traceback (most recent call last):
  File "Blood Cell Detection.py", line 6, in <module>
    from darkflow.net.build import TFNet
  File "D:\Download\Automatic-Identification-and-Counting-of-Blood-Cells\Automatic-Identification-and-Counting-of-Blood-Cells-master\darkflow\net\build.py", line 7, in <module>
    from .framework import create_framework
  File "D:\Download\Automatic-Identification-and-Counting-of-Blood-Cells\Automatic-Identification-and-Counting-of-Blood-Cells-master\darkflow\net\framework.py", line 1, in <module>
    from . import yolo
  File "D:\Download\Automatic-Identification-and-Counting-of-Blood-Cells\Automatic-Identification-and-Counting-of-Blood-Cells-master\darkflow\net\yolo\__init__.py", line 2, in <module>
    from . import predict
  File "D:\Download\Automatic-Identification-and-Counting-of-Blood-Cells\Automatic-Identification-and-Counting-of-Blood-Cells-master\darkflow\net\yolo\predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'`

I downloaded weight, installed cython. I check the folder contain .cy_yolo_findboxes, it exits. 
When i find it on google, i found this link https://github.com/thtrieu/darkflow/issues/168. I did as abagshaw suggest, problem is still unsolved. 

Does anyone know why? Any help is appreciated. 
I use window 10, virtual enviroment of anaconda

**Comment by MahmudulAlam** [comment]
Hi. 
What is the version of the cython you have installed? I am using version ```'0.29.2'```. Worked for me without any problem.

**Comment by ThanhDEHA** [comment]
Thanks, I reinstalled Cython as you said and problem is solved.

**Comment by Baggyyyy** [comment]
> Thanks, I reinstalled Cython as you said and problem is solved.

how to reinstall it in google colab

**Comment by MahmudulAlam** [comment]
What do you want to reinstall?

**Comment by Baggyyyy** [comment]
i am getting the same error sir, 
the code ran fine in the morning..
but its showing  from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'
what should i do sir..

**Comment by MahmudulAlam** [comment]
install cython version==0.29.2 
if it doesn't work, try running the code from the beginning. 
what changes did you make that caused the code not to run?

**Comment by Baggyyyy** [comment]
I didn't make any changes sir,
I tried installing cython command too sir
But still it's showing the same error

**Comment by MahmudulAlam** [comment]
what is your python version?

**Comment by Baggyyyy** [comment]
I am running in colab sir

**Comment by MahmudulAlam** [comment]
check your python version.

**Comment by MahmudulAlam** [comment]
requirement is python 3.6 or 3.7.

**Comment by Baggyyyy** [comment]
The version is python 3.7 only sir
