### ISSUE TITLE
Training file missing

### ISSUE THREAD

**Issue by yuki4ghub15** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#8]
Hi, thanks for good work. I have curiosity on how you get the detection with tiny yolo3. which accuracy is lower than original yolo3 model.  could you share your training file. thanks -

**Comment by MahmudulAlam** [comment]
Hello, 
Thanks for your interest. Yes, the accuracy of the tiny yolo is indeed lower than the original model.  However, training tiny yolo it a lot easier with your dataset than the original one. If you are asking for the weights file (training file), they are already shared. You can access them by clicking [![Download](https://img.shields.io/badge/download-weights-brightgreen.svg?longCache=true&style=flat)](https://mega.nz/#F!2kVUnKjS!z15tM9WLfga3l1gCNSLNGw) 
badge in the readme section or [use this link](https://mega.nz/#F!2kVUnKjS!z15tM9WLfga3l1gCNSLNGw).

I have also shared two wikis on how to run the code and how to train on your dataset. You can find them in the [wiki](https://github.com/MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells/wiki) section.
