### ISSUE TITLE
facing error while importing the module

### ISSUE THREAD

**Issue by deepaksingh09** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#9]
hi thanks  for the work .
even i m using the cython version 0.29.2
  File "<ipython-input-2-a3df6432f9c8>", line 1, in <module>
    from ...utils.im_transform import imcv2_recolor, imcv2_affine_trans

ImportError: attempted relative import with no known parent package

**Comment by MahmudulAlam** [comment]
Hello. @deepaksingh09 

You should have the visual studio installed on your computer as cython uses a c++ compiler in the backend. If you have already visual studio installed on your computer or after installation it still does not work, please share a screenshot of the error message. 

Let me know what happens.
